//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int SoHoaDon { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> MaSanPham { get; set; }
        public Nullable<int> GiaTien { get; set; }
        public Nullable<int> SanPham { get; set; }
    
        public virtual SanPham SanPham1 { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}
